### ISSUE TITLE
Archiver always downloads resources even when not changed.

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-archiver#7]
It looks like the archiver always downloads the content from the url it is given, even if the content hasn't changed.

As a minimum it should check the headers for an ETag header and compare it with the header from the last archive. Ideally it should also send an If-Modified-Since based on any previously set Last-Modified header.

**Comment by davidread** [comment]
This may help efficiency in many servers.

I guess though there is a chance that the server is playing up and is serving headers saying the file is not changed, but it won't actually download. But maybe that's being too paranoid?
